Chore/semaphore v3
semaphore-protocol/boilerplate pull request #18
Opened 2023-01-19 19:15 UTC by vplasencia

## Description

Add script to copy contract artifacts to `subgraph` and `web-app` folders and info in the Readme file about the steps to follow every time the smart contract is deployed.

## Related Issue
Closes #16 

## Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

2023-01-20 11:51 UTC, cedoor requested changes

2023-01-20 11:51 UTC, cedoor commented on package.json
> +        "copy:contract-artifacts": "npx ts-node scripts/copy-contract-artifacts.ts"
```suggestion
"copy:contract-artifacts": "ts-node scripts/copy-contract-artifacts.ts"
```
`npx` shouldn't be necessary.

2023-01-20 11:51 UTC, cedoor commented on scripts/copy-contract-artifacts.ts
> +async function copyArtifactsFiles() {
```suggestion
async function main() {
   try {
        await fs.promises.copyFile(`${contractArtifactsPath}/Feedback.json`, `${subgraphArtifactsPath}/Feedback.json`)
        await fs.promises.copyFile(`${contractArtifactsPath}/Feedback.json`, `${webAppArtifactsPath}/Feedback.json`)
    } catch (err) {
        throw new Error("Error occurred while copying the contract artifacts files")
    }
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error)
        process.exit(1)
    })
```

What about using the Hardhat standard we already used here? https://github.com/semaphore-protocol/semaphore/blob/main/scripts/download-snark-artifacts.ts

2023-01-20 11:51 UTC, cedoor commented on README.md
> +#### Steps to follow every time the smart contract is deployed:
```suggestion

```
The previous list could continue.

2023-01-20 11:51 UTC, cedoor commented on README.md
> +4. Copy the `Feedback.sol` file (contract artifacts) from `apps/contracts/build/contracts/contracts/Feedback.sol` folder to `apps/subgraph/contract-artifacts` and `apps/web-app/contract-artifacts `fo
```suggestion
3. Change the `address` (with the new contract address) and `startBlock` (with the block number of the transaction where the contract was created) in the `apps/subgraph/subgraph.yaml` file.

4. Copy your contract artifacts from `apps/contracts/build/contracts/contracts` folder to `apps/subgraph/contract-artifacts` and `apps/web-app/contract-artifacts `folders manually. Or run `yarn copy:contract-artifacts` in the project root to do it automatically.

5. Deploy the subgraph again.
```

The subgraph should be deployed only after updating the contract artifacts.

2023-01-20 11:51 UTC, cedoor commented on README.md
> +
```suggestion
```

This should already be explained in the previous point (?).

2023-01-20 23:38 UTC, vplasencia commented on README.md
> +#### Steps to follow every time the smart contract is deployed:
True

2023-01-23 10:37 UTC, cedoor approved these changes

2023-01-23 10:37 UTC, merged